### ISSUE TITLE
kicad 5.1.2 incompat

### ISSUE THREAD

**Issue by bfarago** [cyrozap/GPIB-to-USB#2]
Hi,
 please update your project, to keep usable with latest kicad.
There are refs to obsolate libs, and error : "Missing EELAYER END". Nothing can be seen.
(Yes, I updated the submodules in git.)

**Comment by cyrozap** [comment]
The design in this repository is empty. I'm sorry I hadn't communicated that clearly.

I'm closing this issue because I'm archiving this repository.
